// React/src/components/register/Register.js
import React, { useState } from 'react';
import { useDispatch } from 'react-redux';
import { userLogin } from '../../redux/actions/userLogin';
import axiosApp from '../util/axiosApp';
import Statics from '../util/Statics';
import InputLabel from '@material-ui/core/InputLabel';
import TextField from '@material-ui/core/TextField';
import PasswordField from 'material-ui-password-field';
import { FormControl } from '@material-ui/core';

const Register = () => {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const dispatch = useDispatch();

  const onSubmit = (e) => {
    e.preventDefault();
    axiosApp
      .post('/register', {
        firstName,
        lastName,
        email,
        password,
      })
      .then((data) => {
        //console.log(data);
        Statics.saveAccessRefreshToken(data.accessToken, data.refreshToken);
        dispatch(userLogin());
        window.location.href = '/';
      });
  };

  return (
    <div>
      <form className='login-register-form' onSubmit={onSubmit}>
        <TextField
          required
          style={{ width: '100%', marginBottom: '35px' }}
          label='First name'
          value={firstName}
          onChange={(e) => {
            setFirstName(e.target.value);
          }}
        />
        <TextField
          required
          style={{ width: '100%', marginBottom: '35px' }}
          label='Last name'
          value={lastName}
          onChange={(e) => {
            setLastName(e.target.value);
          }}
        />
        <TextField
          required
          type='email'
          style={{ width: '100%', marginBottom: '35px' }}
          label='Email'
          value={email}
          onChange={(e) => {
            setEmail(e.target.value);
          }}
        />

        <FormControl required style={{ width: '100%', marginBottom: '80px' }}>
          <InputLabel htmlFor='standard-adornment-password'>Password</InputLabel>
          <PasswordField
            value={password}
            required
            onChange={(e) => {
              setPassword(e.target.value);
            }}
          />
        </FormControl>

        <input type='submit' value='Register' className='btn btn-block' style={{ background: 'green' }} />
      </form>
      <div className='center'>
        <h3>
          If you have an account.
          <i>
            {' '}
            <a href='/login'>Login now.</a>{' '}
          </i>{' '}
        </h3>
      </div>
    </div>
  );
};

export default Register;

// Angular/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent implements OnInit {
  email = '';
  password = '';
  firstName = '';
  lastName = '';
  hide = true;

  constructor() {}

  ngOnInit(): void {}

  onSubmit() {
    console.log('rjoighrgrg');
  }
}

<div>
  <form ngNativeValidate (ngSubmit)="onSubmit()" class="login-register-form">
    <mat-form-field>
      <mat-label>First name</mat-label>
      <input
        matInput
        required
        id="firstName"
        name="firstName"
        [(ngModel)]="firstName"
        [ngModelOptions]="{ standalone: true }"
      />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Last name</mat-label>
      <input
        matInput
        required
        id="lastName"
        name="lastName"
        type="email"
        [(ngModel)]="lastName"
        [ngModelOptions]="{ standalone: true }"
      />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Email</mat-label>
      <input
        matInput
        placeholder="example@example.com"
        required
        type="email"
        id="email"
        name="email"
        [(ngModel)]="email"
        [ngModelOptions]="{ standalone: true }"
      />
    </mat-form-field>
    <mat-form-field>
      <mat-label>Password</mat-label>
      <input
        matInput
        [type]="hide ? 'password' : 'text'"
        placeholder="example@example.com"
        required
        minlength="4"
        [(ngModel)]="password"
        [ngModelOptions]="{ standalone: true }"
      />
      <mat-icon matSuffix (click)="hide = !hide">{{
        hide ? "visibility_off" : "visibility"
      }}</mat-icon>
    </mat-form-field>

    <input id="submit" type="submit" value="Register" class="btn btn-block" />
  </form>

  <div class="center">
    <h3>
      If you have an account.
      <i> <a href="/login">Login now.</a> </i>
    </h3>
  </div>
</div>
